from __future__ import annotations

CANONICAL_COLUMN_ALIASES: dict[str, tuple[str, ...]] = {
    "vacancy_id": ("vacancy_id", "id", "job_id", "vacancyid"),
    "company": ("company", "company_name", "employer", "hiring_organization"),
    "role_category": (
        "role_category",
        "role_family_primary",
        "role_family",
        "role",
        "category",
    ),
    "city": ("city", "place", "location_city", "locality"),
    "canton": ("canton", "state", "region", "location_canton"),
    "seniority": ("seniority", "seniority_level", "experience_level"),
    "work_mode": ("work_mode", "remote_mode", "remote_policy"),
    "skills": (
        "skills",
        "skill_tags",
        "detected_skills",
        "keywords_matched",
        "tech_skills",
    ),
    "programming_languages": (
        "programming_languages",
        "programming_language",
        "languages",
        "language_skills",
    ),
    "frameworks_libraries": (
        "frameworks_libraries",
        "frameworks",
        "framework_libraries",
        "libraries",
        "framework_library",
    ),
    "salary_min": ("salary_min", "salary_from", "annual_salary_from", "min_salary"),
    "salary_max": ("salary_max", "salary_to", "annual_salary_to", "max_salary"),
    "salary_currency": ("salary_currency", "currency"),
    "salary_unit": ("salary_unit", "salary_period", "salary_frequency", "unit"),
    "salary_text": ("salary_text", "salary", "salary_display"),
}

REQUIRED_COLUMNS: tuple[str, ...] = (
    "company",
    "role_category",
    "city",
    "canton",
    "seniority",
    "work_mode",
    "skills",
)

DISTRIBUTION_COLUMNS: tuple[str, ...] = (
    "company",
    "role_category",
    "city",
    "canton",
    "seniority",
    "work_mode",
)

MISSING_TEXT_VALUES: frozenset[str] = frozenset(
    {
        "",
        "-",
        "--",
        "n/a",
        "na",
        "none",
        "null",
        "nan",
        "unknown",
        "not specified",
        "not_specified",
    }
)

UNKNOWN_LABEL = "Unknown"
PUBLIC_ANALYTICS_MIN_PUBLICATION_DATE = "2026-01-01"
STAFFING_AGENCY_COMPANY_NAMES: frozenset[str] = frozenset(
    {
        "Adecco",
        "Actalent",
        "albedis",
        "Agroos Personal AG",
        "Approach People Recruitment",
        "Approach People Recruitment SA",
        "Aposto Personal GmbH",
        "Art of Work Personalberatung AG",
        "Avalect Personaldienstleistungen",
        "BC Personalmanagement AG",
        "Bellini Personal AG",
        "bruederlinpartner GmbH",
        "Careerplus",
        "Careerplus AG",
        "Consult & Pepper AG",
        "Cubiq Recruitment",
        "Darwin Recruitment",
        "Die Recruiting Partner GmbH",
        "Dorigo AG - Recruiting & Coaching Services Switzerland",
        "Elan Personal AG",
        "Experis",
        "Experis AG",
        "European Tech Recruit",
        "Freestar-Informatik AG",
        "Gassner Personalberatung Est.",
        "Hays",
        "Hays (Schweiz) AG",
        "Härdi Personal",
        "Impact Recruitment GmbH",
        "IPA Internationale Personal Agentur AG",
        "ITech Consult AG",
        "ictjobs (Stellenmarkt)",
        "IQ Plus AG",
        "Job Impuls AG",
        "Jobgether",
        "JobTalente GmbH",
        "Joker Personal AG",
        "KeyCon Personal Consulting Kost",
        "Manpower",
        "Manpower Basel",
        "Manpower SA",
        "Michael Page",
        "Michael Page Switzerland",
        "mühlemann IT-personal",
        "myitjob GmbH",
        "myScience",
        "Nemensis AG",
        "Nexus Personal- & Unternehmensberatung AG",
        "Nordwand Group - the IT & Finance Recruitment Company",
        "ONE Agency GmbH",
        "Opus Personal AG",
        "Page Personnel",
        "Persona services GmbH",
        "Personal Contact Basel AG",
        "Personal Knobel AG",
        "PKS Personal AG",
        "Personal Sigma Schwyz AG",
        "Personal Sigma Sursee AG",
        "persona service GmbH",
        "Placement Services - Personaldienstleistungen Tuna",
        "Prime21",
        "Prime21 AG",
        "Proclinical Staffing",
        "Progress Personal AG",
        "Randstad",
        "Randstad (Schweiz) AG",
        "Randstad Digital Switzerland",
        "Randstad Digital Switzerland AG",
        "Randstad Inhouse Services",
        "Randstad Switzerland",
        "Rocken®",
        "Rockstar Recruiting AG",
        "Roger Renggli Personalberatung GmbH",
        "SMART Recruiting GmbH",
        "Skilled - Recruitment Solutions GmbH",
        "Summit Recruitment AG",
        "TalentCloud Group Recruitment",
        "Technology Staffing Group",
        "The Adecco Group",
        "Universal-Job AG",
        "Werner Rast Personal Beratung Vermittlung AG",
        "Werren & Thomann GmbH, Unternehmens- und Personalberatung",
        "Work Selection",
        "yellowshark",
        "yellowshark® AG",
        "Zollinger Personal GmbH",
        "edp personalberatung gmbh",
        "ict-personalberatung.ch GmbH",
        "smartpersonal gmbh",
    }
)
DEFAULT_TOP_SKILLS = 20
DEFAULT_TOP_SKILL_PAIRS = 50
OPTIONAL_LIST_COLUMNS: tuple[str, ...] = (
    "programming_languages",
    "frameworks_libraries",
)
